# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\nuser_proto\"j\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x10\n\x08username\x18\x06 \x01(\t\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x0fUserListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"d\n\x10UserListResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0c\n\x04next\x18\x02 \x01(\t\x12\x10\n\x08previous\x18\x03 \x01(\t\x12!\n\x07results\x18\x04 \x03(\x0b\x32\x10.user_proto.User\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t2\xdb\x01\n\x0bUserService\x12>\n\x07GetUser\x12\x1f.user_proto.UserRetrieveRequest\x1a\x10.user_proto.User\"\x00\x12H\n\tListUsers\x12\x1b.user_proto.UserListRequest\x1a\x1c.user_proto.UserListResponse\"\x00\x12\x42\n\tLoginUser\x12\x18.user_proto.LoginRequest\x1a\x19.user_proto.LoginResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=26
  _USER._serialized_end=132
  _USERRETRIEVEREQUEST._serialized_start=134
  _USERRETRIEVEREQUEST._serialized_end=167
  _USERLISTREQUEST._serialized_start=169
  _USERLISTREQUEST._serialized_end=219
  _USERLISTRESPONSE._serialized_start=221
  _USERLISTRESPONSE._serialized_end=321
  _LOGINREQUEST._serialized_start=323
  _LOGINREQUEST._serialized_end=373
  _LOGINRESPONSE._serialized_start=375
  _LOGINRESPONSE._serialized_end=435
  _USERSERVICE._serialized_start=438
  _USERSERVICE._serialized_end=657
# @@protoc_insertion_point(module_scope)
